name: 2b2t-Disconnect
main: Disco.Main
version: "0.0.0.1"
api: ["1.0.0"]

load: POSTWORLD
author: coke
description: 2b2t PE's disconnect reason.
website: https://github.com/SumWum
commands:
  dc:
    description: null
    usage: "null"
    permission: dc.command.dc
permissions:
  dc.command.dc:
    description: "info"
    default: true